name: ecommerce
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  carousel_slider: ^1.4.1
  scrolling_page_indicator: ^0.1.2
  dots_indicator: ^1.2.0
  page_view_indicator: ^2.0.4
  provider: ^4.3.2+1
  font_awesome_flutter: ^8.8.1
  http: ^0.12.2
  image_picker: ^0.6.6+4
  dio: ^3.0.10

 
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - Image/dog.png




  fonts:
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Regular.ttf

     - family: Comfortaa
       fonts:
         - asset: fonts/Comfortaa-Regular.ttf
        
     - family: InconsolataCondensed
       fonts:
         - asset: fonts/InconsolataCondensed-Regular.ttf

     - family: Lato
       fonts:
         - asset: fonts/Lato-Regular.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
